/*
        
    1) Create function testMe that creates 3 variables and returns their product

    2) Create function AI that respond "hi" if the parameter is "hello", 
       "I cannot understand" otherwise

    3) Create function tripleSum that receives 3 numbers and returns the sum of them

    4) Create function factorial that calculates the factorial of the given param

    5) Create function calculator with 3 params, two numbers (param1 and param2) and 
       a sign between "+","-","*","/". Return the operation between param1 and param2

    6) Create function absolute that returns the absolute value of the parameter 
       (es.: p = 1 returns 1, p = -27 returns 27)

    7) Create function fizzBuzz that returns fizz if param is multiple of 3, 
       buzz if multiple of 7, fizzbuzz if multiple of 3 and 7. Otherwise returns the same number

    8) Create function positive that returns true if the params is greater than 0

    9) Create function transform that receives a number between 0 and 9 and returns 
       a string containing the number (ex.: 0 returns "zero", 1 returns "one")

    10) Create function sum that receives an array as parameter and return the sum of 
        the elements (only numerical ones)

    11) Create function min that receives an array and returns the minumum value in the array

    12) Create function arrayFi that receives an object and trasforms it in an array. 
        Example: arrayFi({ name: "John", surname: "Doe"}) returns [ "name", "john", "surname", "Doe"]

    13) Create function objectyFi that revert the array generated by arrayFi into and object

    14) Create function revertArray that revert the elements into an array

    15) Create function swappy that receives 2 positions and swap them into the array. 
        Example: array = [ 1, 2, 3, 4]. Swappy(0, 3) ==> [3, 2, 1, 4]

*/

//-----

function testMe() {
   let a = Math.random()*100;
   let b = Math.random()*100;
   let c = Math.random()*100;

   return a*b*c
}

function AI(x) {
   if(x=='hello') {
      console.log('hi');
   }
   else {
      console.log('I cannot understand');
   }
}

function tripleSum(a, b, c) {
   return a+b+c
}

function factorial(x) {
   for(var i=0; x>0; ) {
      i += x--
   }

   return i
}

function calculator(num1, num2, operation) {
   if(operation=='+') {
      return num1+num2
   }

   if(operation=='-') {
      return num1-num2
   }

   if(operation=='*') {
      return num1*num2
   }

   if(operation=='/') {
      return num1/num2
   }
}

function absolute(ab) {
   if(ab>=0) {
      return ab
   }
   else return -ab
}

function fizzBuzz() {
   
}